### ISSUE TITLE
[Admin portal] Dates are in UTC

### ISSUE THREAD

**Issue by Timst** [djact/maskes#23]
![image](https://user-images.githubusercontent.com/1691713/91515185-6ded5000-e89d-11ea-857b-da06c7f2b346.png)

![image](https://user-images.githubusercontent.com/1691713/91515189-704faa00-e89d-11ea-93ea-5f930a60a00a.png)

We should probably use PST if possible.

**Comment by pianote** [comment]
Added middleware to fix issue.
