### ISSUE TITLE
[Profile page][Design] Toggled off options look like they're disabled

### ISSUE THREAD

**Issue by Timst** [djact/maskes#6]
It's maybe just me, but when I see a grayed out option like here:

![image](https://user-images.githubusercontent.com/1691713/91511382-64abb580-e894-11ea-8228-f8d4d91d91fe.png)

My first thought is that the toggle is disabled (as in, it can't be changed). Also I'm not sure if it makes sense that the colored, "on"-looking design is private, and the grey out is public?

**Comment by pianote** [comment]
Changed to on/off privacy mode
